# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test SQLModel.Tests/SQLModel.Tests.csproj -c Release --verbosity normal
    - name: Create the package
      run: dotnet pack --no-build -c Release --configuragiton Release dotnet_orm
    - name: Publish the package to GPR
      run: dotnet nuget push SQLModel/bin/Release/*.nupkg --source https://www.nuget.org/packages/theandru-dotnet-orm --api-key ${{secrets.NUGET_API_KEY}}
