name: Tests and publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
  
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test UniqModel.Tests/UniqModel.Tests.csproj -c Release --verbosity normal

    - name: Publish the package to GPR
      run: |
        dotnet nuget push UniqModel/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
      